# --- Serving options --- #
url: "http://cgte88586.github.io"
baseurl: ""

# Name of website
title: "Zhou (Joe) Li"

# Short description of your site
description: "Ph.D. Student in Statistics at NC State"

# --- Navigation bar options --- #

avatar: "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAIwAAAAJDFkMmUwMTY3LWNkMzYtNGIwZC1iOTFjLWNjMmI2MjFkNTA4ZQ.jpg"

# List of links in the navigation bar
navbar-links:
  Home: ""
  Resume: "https://github.com/cgte88586/resume"
  About Me: "aboutme"
  
# --- Footer options --- #

author:
  name: Zhou (Joe) Li
  email: "zli15@ncsu.edu"
  facebook: benlz1989  # eg. daattali
  github: cgte88586    # eg. daattali
  twitter: yourname   # eg. daattali
  linkedin: in/zhouli89  # eg. "pub/dean-attali/8/946/143"
  stackoverflow: yourlink  # eg. "3943160/daattali"

footer-links-active:
  rss: true
  facebook: true
  email: true
  twitter: false
  github: true
  linkedin: true
  stackoverflow: false

url-pretty: "http://cgte88586.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Misc --- #

# Fill in your Disqus shortname (NOT the userid) if you want to support Disqus comments
disqus: "jlispersonalwebsite"

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-73356853-1"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "America/New_York"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
gems: [jekyll-paginate]
paginate: 5

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "default"

# Exclude these files from production site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - Vagrantfile
